package com.bridgelabz.employeepayrollapp.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

// UC-6 Use Lombok Library to auto-generate getters, setters, toString, equals, and hashCode methods
// also no-argument constructor

@Entity
@Table(name = "employees")

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Name is required")
    private String name;

    @Min(value = 10000, message = "Salary must be at least 10000")
    private double salary;

    // toString method is also auto-generated by Lombok.

    // Additional constructor to handle (String, double) parameters
    public Employee(String name, double salary) {
        this.name = name;
        this.salary = salary;
    }
}
